#!/usr/bin/env python
# -*- coding: utf-8 -*-
# This file is part of the Kount python sdk project
# https://github.com/Kount/kount-ris-python-sdk/)
# Copyright (C) 2017 Kount Inc. All Rights Reserved.
"""autogenerated rules from xml_filename = 'validate.xml' in settings.py"""
from __future__ import absolute_import, unicode_literals, division, print_function
import os
from kount.util.xmlparser import xml_to_dict
from kount.settings import RESOURCE_FOLDER, XML_FILENAME


__author__ = "Kount SDK"
__version__ = "1.0.0"
__maintainer__ = "Kount SDK"
__email__ = "sdkadmin@kount.com"
__status__ = "Development"

XML_FILENAME_PATH = os.path.join(os.path.dirname(__file__), '..', '..',
                                 RESOURCE_FOLDER, XML_FILENAME)
XML_DICT, REQUIRED, NOTREQUIRED = xml_to_dict(XML_FILENAME_PATH)
